services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: kanban-oracle
    environment:
      ORACLE_PASSWORD: admin1234
      APP_USER: kanban
      APP_USER_PASSWORD: kanban1234
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

  redis:
    image: redis:7-alpine
    container_name: kanban-redis
    ports:
      - "6379:6379"

volumes:
  oracle-data: